name: build

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            ghc: '8.6'
            continue-on-error: false
          - os: windows-latest
            ghc: '8.8'
            continue-on-error: false
          - os: windows-latest
            ghc: '8.10'
            continue-on-error: false
          - os: windows-latest
            ghc: latest
            continue-on-error: true
          - os: macos-latest
            ghc: '8.6'
            continue-on-error: false
          - os: macos-latest
            ghc: '8.8'
            continue-on-error: false
          - os: macos-latest
            ghc: '8.10'
            continue-on-error: false
          - os: macos-latest
            ghc: latest
            continue-on-error: true
          - os: ubuntu-latest
            ghc: '8.6'
            continue-on-error: false
          - os: ubuntu-latest
            ghc: '8.8'
            continue-on-error: false
          - os: ubuntu-latest
            ghc: '8.10'
            continue-on-error: false
          - os: ubuntu-latest
            ghc: latest
            continue-on-error: true

    runs-on: ${{ matrix.os }}

    continue-on-error: ${{ matrix.continue-on-error }}

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal update
      - run: make build-deps
      - run: make build
